# SimplePortScanner Configuration File
# Comments start with '#'

# Target IPv4 address to scan
targetIp = 127.0.0.1

# Port range to scan
startPort = 1
endPort = 1024

# Connection timeouts in milliseconds
tcpTimeoutMs = 200
udpTimeoutMs = 500

# Protocols to scan (true / false)
scanTcp = true
scanUdp = false
